- esmf_regrid/tests/__init__.py
- esmf_regrid/tests/results/test_GridInfo/small_grid.txt
- esmf_regrid/tests/test_GridInfo.py
- noxfile.py
Add a single test to establish a testing structure and test the CI.
> Add first test

- .github/ISSUE_TEMPLATE/---bug-report.md
- .github/ISSUE_TEMPLATE/---custom-issue.md
- .github/ISSUE_TEMPLATE/--feature-request.md
This PR adds new issue templates for the repository.
To do after merge:
> Update issue templates

- .cirrus.yml
- .gitignore
- noxfile.py
- requirements/py36.yml
- requirements/py37.yml
- requirements/py38.yml
This PR cherry-picks commit `be03823f7515f11543800dd39987f449a3c0aad3` from the `unstructured_scheme` feature branch and applies its goodness to `main`.
The benefit of this is that there is no need to wait for the feature branch to be merged back to `main` to use this functionality in `main`.
See #33
> Unstructured scheme iris source (#33)

- esmf_regrid/tests/unit/experimental/unstructured_scheme/test__mesh_to_MeshInfo.py
Fixes a test broken by changing MeshInfo.size a property.
> Unstructured Scheme - Fix Test

- esmf_regrid/experimental/unstructured_scheme.py
- esmf_regrid/tests/unit/experimental/unstructured_scheme/test_MeshToGridESMFRegridder.py
This improves the documentation and test coverage of the unstructured scheme by adding docstrings, updating some comments and adding a test for mdtol checking.
> Unstructured Scheme - Additional Polish (docstrings and test coverage)

- esmf_regrid/tests/unit/experimental/__init__.py
- esmf_regrid/tests/unit/experimental/unstuctured_regrid/__init__.py
Add __init__ files which were previously missing from the test structure.
> Add __init__ to tests

- .cirrus.yml
Set the git user and email to enable asv gh-pages to run successfully.
> ASV gh-pages user and email

- esmf_regrid/esmf_regridder.py
Add docstrings which were still missing.
> Add docstrings

- docs/src/CHANGELOG.md
A simplified version of #104 based on this template https://gist.github.com/juampynr/4c18214a8eb554084e21d6e288a18a2c.
> Add changelog

- noxfile.py
Resets the flag switched in #144 in order to refresh the nox cache.
> Reset flag

- README.md
Add enough documentation to the readme so that new users should be able to make use of the most important features by following the example.
> Add brief overview to readme

- .cirrus.yml
- noxfile.py
Just some stuff I spotted during Support work.
> Fixes to get Nox sessions working.

- CHANGELOG.md
Adds a changelog entry for #198
> Update changelog for #198

- CHANGELOG.md
- esmf_regrid/__init__.py
> Update to v0.7

- esmf_regrid/schemes.py
See https://github.com/SciTools/iris/pull/5767
> Fix usage of map_blocks

- CITATION.cff
- LICENSE
- README.md
> Add zenodo badge, update LICENSE

- esmf_regrid/experimental/io.py
load_regridder now works for any regridder type, fixes docstring to reflect this.
> Fix load_regridder docstring

- benchmarks/asv.conf.json
- benchmarks/custom_bms/README.md
- benchmarks/custom_bms/install.py
- benchmarks/custom_bms/tracemallocbench.py
> Add `benchmarks/custom_bms` from template

- .github/workflows/benchmark.yml
- .github/workflows/ci-wheels.yml
- pyproject.toml
Reference [download-artifact](https://github.com/actions/download-artifact)
> support unique name for upload/download artifact

- .readthedocs.yml
See `rtd` [configuration](https://docs.readthedocs.com/platform/stable/config-file/v2.html#) for further details.
> update rtd configuration

- benchmarks/asv_delegated_conda.py
- benchmarks/benchmarks/generate_data.py
- pyproject.toml
- src/esmf_regrid/__init__.py
- src/esmf_regrid/experimental/unstructured_scheme.py
- src/esmf_regrid/schemes.py
- src/esmf_regrid/tests/unit/schemes/test__mesh_to_MeshInfo.py
Adds support for exception chaining, thus producing more helpful tracebacks.
> Fix try except handling

- pyproject.toml
> Ignore ruff code PLC0415

- benchmarks/benchmarks/generate_data/__init__.py
> Adopt templating changes (#540)

- docs/src/conf.py
Cartopy docs have a new home 🏠
> DOC: update intersphinx mapping for Cartopy
