.cirrus.yml
This PR adds two levels of control to force a refresh of `cirrus-ci` task caches:
1. Incorporate the `date` year `+%Y`, and week number `+%U` as part of a cache `fingerprint`, and using the `CACHE_AGE` on the week number to partition the week number into like week periods - for automated refreshes
1. Use the `X_CACHE_BUILD` number as part of a cache `fingerprint` to force a cache upload - for manual refreshes
The expected typical use case for bumping the cache build number would be to force a cache upload within a `CACHE_AGE` period. The build number should then be reset after the `CACHE_AGE` period has elapsed.
=> add cache refresh

noxfile.py
This PR streamlines the `nox` session for `tests`, taking advantage of re-using any associated cached `conda` environment by not always installing the environment requirements.
Rather, it first detects whether `pytest` is available, and if not installs the associated `conda` environment.
=> check nox conda requirements

noxfile.py
This PR makes use of the convenience `session.bin` property.
=> use nox session.bin

esmf_regrid/esmf_regridder.py, esmf_regrid/tests/__init__.py, esmf_regrid/tests/integration/__init__.py, esmf_regrid/tests/integration/esmf_regridder/__init__.py, esmf_regrid/tests/integration/esmf_regridder/test_Regridder.py, esmf_regrid/tests/unit/esmf_regridder/__init__.py, esmf_regrid/tests/unit/esmf_regridder/test_Regridder.py
This addresses #20. It allows the regridding of masked arrays. It also supports a choice of normalisation options (as described [here](http://earthsystemmodeling.org/esmf_releases/public/ESMF_8_0_1/esmpy_doc/html/NormType.html)). This PR also improves the test coverage for the regridder which was missing in the initial code.
=> Add support for masked data

esmf_regrid/esmf_regridder.py, esmf_regrid/experimental/__init__.py, esmf_regrid/experimental/unstructured_regrid.py, esmf_regrid/tests/results/unit/experimental/unstructured_regrid/test_MeshInfo/small_mesh.txt, esmf_regrid/tests/unit/experimental/unstuctured_regrid/test_MeshInfo.py
This adds back end support for UGRID style unstructured meshes. It is built in anticipation of Iris adding UGRID support and therefore the code is separated into an experimental directory. Adding and testing against this code now ensures that the design of iris-esmf-regrid will maintain the flexibility to add UGRID support when Iris allows it.
This builds on top of #22 and is therefore a draft.
=> Add unstructured mesh support with MeshInfo

.cirrus.yml
This PR is a fix to the `.cirrus.yml`, where the output of `$(date +%U)` returns `week number of year, with Sunday as first day of week (00..53)` can be interpreted as an octal number that is out of range e.g., `08`.
This causes `bash` to raise and error, and subsequently for all `cirrus-ci` tasks to fail.
=> fix bash octal date

esmf_regrid/experimental/unstructured_scheme.py, requirements/py36.yml, requirements/py37.yml, requirements/py38.yml
Introduces the structure of the unstructured regridding scheme with some minimal code. Further tasks are separable and are described by TODO comments.
=> Unstructured scheme skeleton

esmf_regrid/experimental/unstructured_scheme.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test__cube_to_GridInfo.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_cube_to_GridInfo.py
This copies the most basic functionality from #26 to integrate rectilinear grid handling. This allows development of the unstructured regridder to continue.
=> Unstructured Scheme - Basic GridInfo Handling

.cirrus.yml, .gitignore, noxfile.py, requirements/py36.yml, requirements/py37.yml, requirements/py38.yml
This PR provides `iris` source GitHub artifact support, to allow testing against a specific `iris` GitHub repo branch name, tag name or commit sha.
It also contains condidtional task execution, better caching, and controls for conda environment verbosity.
The `flake8` and `black` linting tasks have been combined, and the long/variable running `osx` task as been retired.
=> Unstructured scheme iris source

.github/workflows/greetings.yml
This PR remove `\n` escape sequences from the `greetings` messages, as they are treated literally.
=> update greetings issue and pr message

.flake8, .pre-commit-config.yaml, setup.py
This PR ensures that the `setup` is always executed on `import` and when run as a script.
In addition, the `pre-commit-hooks` version is updated, and additional ignores are added for `flake8`.
=> module level setup

.cirrus.yml, esmf_regrid/experimental/unstructured_scheme.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test__mesh_to_MeshInfo.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_mesh_to_MeshInfo.py
Introduces similar functionality to #32 for the handling of iris Mesh objects. That is, the translation of Mesh objects to MeshInfo objects (extraction of Mesh objects from cubes will be done in a future PR). Also activates #33 so that testing is now done against the iris feature branch `mesh-data-model` which contains the Mesh object
=> Unstructured Scheme - Basic MeshInfo Handling

esmf_regrid/experimental/unstructured_scheme.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test__create_cube.py
Fleshes out the creation of cubes. Now adds grid coordinates from the target cube and copies over metadata and scalar coords from the source cube. Code is mostly copied from a similar iris functionality here https://github.com/SciTools/iris/blob/master/lib/iris/analysis/_regrid.py#L360-L363.
=> Unstructured Scheme - Cube Creation 2D

esmf_regrid/esmf_regridder.py, esmf_regrid/experimental/unstructured_regrid.py, esmf_regrid/tests/integration/esmf_regridder/test_Regridder.py, esmf_regrid/tests/unit/esmf_regridder/test_Regridder.py, esmf_regrid/tests/unit/experimental/unstuctured_regrid/test_MeshInfo.py
Split from #28 to reduce the complexity of the individual PRs. This does not handle any extra dimensions and is only responsible for reordering the existing dimensions and adding a check.
=> Latlon reorder simplified

README.md
This PR adds the `pre-commit.ci` badge to the `README.md`.
`iris-esmf-regrid` is already subscribed to this service.
=> add pre-commit.ci badge

esmf_regrid/experimental/unstructured_scheme.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/__init__.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_MeshToGridESMFRegridder.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test__regrid_unstructured_to_rectilinear__prepare.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_regrid_unstructured_to_rectilinear.py
This PR adds support for fetching meshes and mesh dimensions from iris. Originally we had planned on using a helper function `_get_mesh_and_dim` to do this, however iris has updated to the point where this functionality is given in one line, so for clarities sake I have replaced the helper function. Instead of testing the helper function, I have tested `_regrid_unstructured_to_rectilinear__prepare`, where `_get_mesh_and_dim` would have been called. I have also added a test for `regrid_unstructured_to_rectilinear` to show that the whole regridder now functions as a result. Full test coverage can be added in a further PR.
=> Unstructured Scheme - Mesh Fetching

.cirrus.yml
Just to cover ourselves, let's add the `uname -r` to the conda cache fingerprint
=> update conda cache fingerprint

esmf_regrid/esmf_regridder.py, esmf_regrid/experimental/unstructured_regrid.py, esmf_regrid/tests/integration/esmf_regridder/test_Regridder.py, esmf_regrid/tests/unit/esmf_regridder/test_Regridder.py, esmf_regrid/tests/unit/experimental/unstuctured_regrid/test_MeshInfo.py
Fixes #27. This PR changes the order in which the regridder expects the dimensions of incoming and outgoing data to be ordered to better reflect those described by [CF conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#dimensions). That is, data is expected to be ordered such that longitude is the last dimension and latitude is the second to last dimension. A side effect of the more comprehensive approach I have taken is that it is now possible to regrid data with additional non-horizontal dimensions (which has been accounted for with additional tests).
This reordering is largely confined to the code in the `_flatten_array`/`_unflatten_array` methods. These have become more complex than before, which I believe is due to a mismatch in the way …
=> Extra dimension handling (previously Dimension priority reorder)

esmf_regrid/experimental/unstructured_scheme.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test__create_cube.py
Expands on #39 by adding the ability to handle cubes with additional dimensions. Specifically, this copies from the source cube all DimCoords and AuxCoords which do not span the mesh dimension. Derived coordinates are a more complicated case which may be added in a future PR.
=> Unstructured Scheme - Cube Creation 3D

esmf_regrid/experimental/unstructured_scheme.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_MeshToGridESMFRegridder.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_regrid_unstructured_to_rectilinear.py
Provide support for cubes with extra dimensions. This change allows the regridding of cubes whose `mesh_dim` is any dimension. This is done by transposing the data before and after the regridding opperation. In future, this may be handled by the regridder itself (as opposed to the regridding scheme), however, keeping this functionality in a helper function allows the feature branch to stay more closely aligned with main.
=> Unstructured Scheme - Extra Dims

pyproject.toml
This adds the `.nox` directory to the excludes in `pyproject.toml` alongside `.tox` to avoid unnecessary checks of embedded python files.
Closes #71
=> Add nox to excludes

.cirrus.yml, benchmarks/asv.conf.json, noxfile.py, pyproject.toml
* Enable benchmark integration into CI.
* Post-merge full run including publishing to a `gh-pages` branch.
If this ends up running too long we can review. Perhaps a smaller range, skipping commits, or something completely different.
* A fix for `pyproject.toml`, without which Black will run on all ASV environments as well as the source code.
=> CI Benchmarking

.cirrus.yml, esmf_regrid/tests/integration/experimental/__init__.py, esmf_regrid/tests/integration/experimental/unstructured_scheme/__init__.py, esmf_regrid/tests/integration/experimental/unstructured_scheme/test_regrid_unstructured_to_rectilinear.py
Addresses the integration test part of #61 for the unstructured regridder. Adds support for testing with files from iris-test-data.
=> Unstructured scheme integration test

.cirrus.yml
From testing I have found that by default [Cirrus does not have push/write permissions](https://cirrus-ci.com/task/5279086701445120?logs=benchmarks#L57-62).
These permissions can be granted by [generating an access token for Cirrus](https://cirrus-ci.org/api/#authorization). However this feels like a security loophole, since as far as I can see there would be nothing preventing a malicious push, by proposing this as a change to `cirrus.yml` within a PR. The GitHub actions documentation talks extensively about such risks ([e.g.](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks)), and has securities in place, but I can't find any such mention in Cirrus' documentation.
It may be possible to write a …
=> Don't attempt ASV results publish after merging.

noxfile.py
Noticed this small issue: in one of the noxfile functions, it names a variable `dir`. [dir is a built in function](https://docs.python.org/3/library/functions.html#dir) so it shouldn't be used to as a variable name, as it overrides the builtin function.
=> Rename lockfile_dir to avoid builtin name

esmf_regrid/experimental/unstructured_scheme.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_GridToMeshESMFRegridder.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_regrid_rectilinear_to_unstructured.py
Adds a scheme for regridding from a cube with a grid to a target cube with a mesh. Ultimateley, the regridding schemes may be unified to one which identifies the whether the source and target have a grid or a mesh in them. This scheme adds the third of four possible combinations with only mesh to mesh regridders remaining to be added.
=> Add grid to mesh scheme

benchmarks/benchmarks/ci/esmf_regridder.py
Adds benchmarks for the performing of regridding (after initialisation of a regridder). This is with a view to measuring the performance of different regridding solutions (i.e. sparse vs scipy.sparse). The benchmark is written to include cases involving higher to lower resolution, lower to higher, similar resolutions and a case where parts of the grid are high to low res and other parts are low to high res due to a rotated pole.
=> Add regridding benchmark

benchmarks/benchmarks/ci/esmf_regridder.py
Similar to #98 except for cubes with lazy data.
=> Benchmark lazy regridding

benchmarks/benchmarks/ci/esmf_regridder.py, esmf_regrid/_esmf_sdo.py, esmf_regrid/schemes.py, esmf_regrid/tests/unit/schemes/test_regrid_rectilinear_to_rectilinear.py
Provides lazy regridding through essentially the same means as in iris (introduced in this PR https://github.com/SciTools/iris/pull/3701).
=> Support lazy regridding

.cirrus.yml, benchmarks/benchmarks/ci/esmf_regridder.py, benchmarks/benchmarks/long/esmf_regridder.py, noxfile.py
Add performance tests for preparing a regridder to the CI performance tests and add long running performance tests (with the ability to run them separately via nox) which test the scalability of preparing and performing with real and lazy data for all the regridders.
=> Add performance tests

.cirrus.yml, .gitignore, benchmarks/benchmarks/ci/esmf_regridder.py, benchmarks/benchmarks/generate_data.py, benchmarks/benchmarks/long/esmf_regridder.py, codecov.yml, esmf_regrid/tests/unit/experimental/io/test_round_tripping.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test__mesh_to_MeshInfo.py, noxfile.py
Add benchmarks for the functions `esmf_regrid.experimental.io.save_redridder` and `esmf_regrid.experimental.io.l_roadedridder`.
=> Add load/save benchmarks

esmf_regrid/experimental/unstructured_scheme.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_MeshToGridESMFRegridder.py
=> Fix issue 135 (mesh to grid chunking problems)

esmf_regrid/experimental/unstructured_scheme.py, esmf_regrid/tests/unit/experimental/io/test_round_tripping.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_MeshToGridESMFRegridder.py
Now that iris provides proper mesh equality comparison, this can be done during the MeshToGridESMFRegridder call.
=> Check mesh equality on MeshToGridESMFRegridder call

esmf_regrid/_esmf_sdo.py, esmf_regrid/schemes.py, esmf_regrid/tests/unit/_esmf_sdo/test_GridInfo.py, esmf_regrid/tests/unit/schemes/test_ESMFAreaWeightedRegridder.py, esmf_regrid/tests/unit/schemes/test__cube_to_GridInfo.py, esmf_regrid/tests/unit/schemes/test_regrid_rectilinear_to_rectilinear.py, requirements/py36.yml, requirements/py37.yml, requirements/py38.yml
Adds support for either the source or target grid to be curvilinear (described by 2d coordinates).
=> Add Curvilinear Support

noxfile.py
Benchmarks are currently over-sensitive and regularly flag false positive regressions.
=> Increase standard benchmark regression tolerance

noxfile.py
Handles the breaking change from conda-lock `v1.0`. See SciTools/iris#4644.
=> Use conda-lock `--kind=explicit`

CHANGELOG.md, esmf_regrid/experimental/unstructured_scheme.py, esmf_regrid/schemes.py, esmf_regrid/tests/unit/schemes/test_ESMFAreaWeightedRegridder.py
=> Allow regridding of cubes with multiple coordinates per axis

.cirrus.yml
Fixes an oversight where Cirrus' benchmarking script depended entirely on `$CIRRUS_BASE_SHA`, which only exists on pull requests.
=> Enable benchmarking to run on `main`

.cirrus.yml, .pre-commit-config.yaml, benchmarks/asv_delegated_conda.py, benchmarks/benchmarks/__init__.py, benchmarks/benchmarks/esmf_regridder/__init__.py, benchmarks/benchmarks/esmf_regridder/scalability.py, benchmarks/benchmarks/generate_data.py, noxfile.py, requirements/py310.yml, requirements/py38.yml, requirements/py39.yml
In line with Iris, this PR proposes relying purely on [pre-commit.ci](https://pre-commit.ci/) (already enabled on this repo) for linting tasks, doing away with independently managed Nox sessions.
This reduces duplication, and removes the risk of divergence between the Nox sessions and the pre-commit setup (which recently caused [this CI failure](https://github.com/SciTools-incubator/iris-esmf-regrid/pull/235/checks?check_run_id=11157987258) - different linter versions were insisting on different standards).
Iris' decision-making history:
* Use pre-commit instead of an independent setup:
SciTools/iris#4181
* Rely purely on pre-commit.ci without an additional Nox session:
SciTools/iris#4503
=> Remove flake8 and black Nox sessions.

esmf_regrid/experimental/unstructured_scheme.py, esmf_regrid/schemes.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_GridToMeshESMFRegridder.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_MeshToGridESMFRegridder.py, esmf_regrid/tests/unit/schemes/test_regrid_rectilinear_to_rectilinear.py
Curvilinear regridding is currently bugged when the data is lazy. I think this might also be fixed in #198, but this should also fix it in the short term. #198 will have to be refactored in light of this.
=> Fix curvilinear lazy regridding

README.md, docs/src/conf.py
Readthedocs doesn't `activate` Conda environments and also doesn't use `conda run`. As a consequence, crucial environment variables are not set, preventing the successful building of the documentation.
This PR adds the environment variables in Sphinx' `conf.py`, providing a workaround for that problem. This might need to be updated in the future if either different variables are needed (e.g. Proj recently moved from `PROJ_LIB` to `PROJ_DATA`), or if Readthedocs addresses this, e.g. in readthedocs/readthedocs.org#5339.
Fixes #251
=> Add env vars to sphinx config

CHANGELOG.md, esmf_regrid/esmf_regridder.py, esmf_regrid/experimental/unstructured_scheme.py, esmf_regrid/schemes.py, esmf_regrid/tests/unit/experimental/io/test_round_tripping.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_GridToMeshESMFRegridder.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_MeshToGridESMFRegridder.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_regrid_rectilinear_to_unstructured.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_regrid_unstructured_to_rectilinear.py, esmf_regrid/tests/unit/schemes/__init__.py, esmf_regrid/tests/unit/schemes/test_ESMFAreaWeighted.py, esmf_regrid/tests/unit/schemes/test_ESMFAreaWeightedRegridder.py, esmf_regrid/tests/unit/schemes/test_ESMFBilinear.py, esmf_regrid/tests/unit/schemes/test_ESMFBilinearRegridder.py, esmf_regrid/tests/unit/schemes/test_ESMFNearest.py, esmf_regrid/tests/unit/schemes/test_ESMFNearestRegridder.py, esmf_regrid/tests/unit/schemes/test__ESMFRegridder.py
Creates the minimal version of nearest neighbour regridding described in #213.
This also incidentally fixes a slight error in the refactoring where ESMFBilinear didn't have a `use_src_mask` and `use_tgt_mask` keyword.
=> Add nearest neighbour regridding

README.md, docs/src/conf.py, docs/src/developers_guide/index.rst, docs/src/index.rst, docs/src/installing.rst, docs/src/userguide/examples.rst, docs/src/userguide/index.rst, docs/src/userguide/scheme_comparison.rst, docs/src/userguide/tutorials.rst, docs/src/whatsnew/index.rst, esmf_regrid/__init__.py
=> Add documentation skeleton

esmf_regrid/experimental/unstructured_scheme.py, esmf_regrid/schemes.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_GridToMeshESMFRegridder.py, esmf_regrid/tests/unit/schemes/__init__.py, esmf_regrid/tests/unit/schemes/test_ESMFAreaWeighted.py, esmf_regrid/tests/unit/schemes/test_ESMFAreaWeightedRegridder.py, esmf_regrid/tests/unit/schemes/test_ESMFBilinear.py, esmf_regrid/tests/unit/schemes/test_ESMFNearest.py
=> Add option to initialise from mesh

noxfile.py
The `--strict` parameter is being removed from ASV in the imminent `v0.6` release (airspeed-velocity/asv#1205) - it is becoming the default behaviour.
=> ASV v0.6 - no longer use strict parameter

CHANGELOG.md, esmf_regrid/experimental/unstructured_regrid.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_GridToMeshESMFRegridder.py, esmf_regrid/tests/unit/experimental/unstructured_scheme/test_MeshToGridESMFRegridder.py, esmf_regrid/tests/unit/schemes/test__mesh_to_MeshInfo.py
=> Fix start index bug

esmf_regrid/schemes.py, esmf_regrid/tests/unit/schemes/__init__.py, esmf_regrid/tests/unit/schemes/test_ESMFAreaWeighted.py, esmf_regrid/tests/unit/schemes/test_ESMFBilinear.py, esmf_regrid/tests/unit/schemes/test_ESMFNearest.py, esmf_regrid/tests/unit/schemes/test__cube_to_GridInfo.py
Addresses #222 
Some projections, like OSGB, have units which cannot be converted to degrees (i.e. meters) and cause regridding to fail. This PR assumes that where a coordinate system exists, units ought to already be compatible with it.
=> Allow regridding for projections in non-degree type units

.github/workflows/ci-citation.yml, CITATION.cff, MANIFEST.in, README.md
This pull-request adds a `CITATION.cff` to the repository so that it may be cited in academic publications.
Note that, it also includes a citation GHA that parses the `CITATION.cff` file when it is altered in a pull-request or push to ensure that it is valid.
Reference:
- [GitHub Docs - About CITATION files](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)
- [What is a CITATION.cff file?](https://citation-file-format.github.io/)
- [Citation File Format](https://github.com/citation-file-format/citation-file-format/tree/main#citation-file-format)
Closes https://github.com/SciTools-incubator/iris-esmf-regrid/issues/309
=> Add CITATION.cff

benchmarks/asv.conf.json
Fixes asv by implementing a `build_command` in `asv.conf.json` to use the `setup.py` file. Copies a simplified version of https://github.com/SciTools/iris/pull/5776
=> Fix asv with custom build

esmf_regrid/experimental/unstructured_regrid.py, esmf_regrid/experimental/unstructured_scheme.py, esmf_regrid/schemes.py, esmf_regrid/tests/unit/experimental/unstructured_regrid/test_MeshInfo.py, esmf_regrid/tests/unit/schemes/test__mesh_to_MeshInfo.py
=> Fix unmasked connectivity bug

benchmarks/benchmarks/esmf_regridder/__init__.py, benchmarks/benchmarks/generate_data.py, esmf_regrid/__init__.py, esmf_regrid/experimental/io.py, esmf_regrid/experimental/unstructured_scheme.py, esmf_regrid/schemes.py, esmf_regrid/tests/integration/experimental/unstructured_scheme/test_regrid_unstructured_to_rectilinear.py, esmf_regrid/tests/unit/schemes/test__mesh_to_MeshInfo.py
Adapt to the movement of `iris.experimental.ugrid` to `iris.mesh`.
=> Adapt to changes in iris structure

.github/workflows/refresh-lockfiles.yml
I'm afraid that by far the easiest way to test this is to merge and then run Workflow Dispatch. If we discover problems then I will put in the work to set up a testing instance for myself, but I'd rather do that in the second instance.
=> Authorise the lock file pull request using the SciTools App token

docs/src/conf.py, esmf_regrid/__init__.py
=> Fix for older iris versions (<3.10)

benchmarks/benchmarks/__init__.py, benchmarks/benchmarks/esmf_regridder/scalability.py
Noticed this while setting up the official templated benchmark files.
=> Use new inbuilt ASV benchmark skipper

esmf_regrid/tests/unit/schemes/test_ESMFAreaWeighted.py, esmf_regrid/tests/unit/schemes/test_ESMFBilinear.py, esmf_regrid/tests/unit/schemes/test_ESMFNearest.py, pyproject.toml
Kinda surprised this ever worked.
To be fair, `mypy` was kinda-sorta compliaining about it in a non-obvious way, but I think this explains the inclusion of the `no_namespace_packages` option being enabled ... which is no longer the case.
=> fix unit test schemes dunder imports

.github/dependabot.yml, pyproject.toml
Reference, see:
- [groups](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#groups--)
- [commit-message](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#commit-message--)
=> use groups for dependabot

benchmarks/benchmarks/generate_data/__init__.py
I hope/think this fixes the outstanding benchmarking failures, currently seen on #518 and various others.
The logic of what `run_function_elsewhere` is doing is that it must always have the `ESMFMKFILE` env var pointing at the correct config settings for the install of ESMPy/ESMF within the Python it is going to run.
So, it makes sense to save + restore that, 
but it should be set to the one installed in the called "data-gen" python.
=> Use esmf-mkfile from data-gen-python in 'run_function_elsewhere'.
